### ISSUE TITLE
Wrong json format in TransactionFee

### ISSUE THREAD

**Issue by stracedude** [move-ton/ton-client-go#9]
Hi! Thanks for the library, faced with such an error:
` json: cannot unmarshal number into Go struct field TransactionFees.fees.in_msg_fwd_fee of type string`

```go
	TransactionFees struct {
		InMsgFwdFee      string `json:"in_msg_fwd_fee"`
		StorageFee       string `json:"storage_fee"`
		GasFee           string `json:"gas_fee"`
		OutMsgsFwdFee    string `json:"out_msgs_fwd_fee"`
		TotalAccountFees string `json:"total_account_fees"`
		TotalOutput      string `json:"total_output"`
	
```

Maybe big.Int type?

**Comment by stracedude** [comment]
Sorry, go get download last release, in master is fixed.

**Comment by markgenuine** [comment]
Thanks you for attention, in the future we update to version sdk 1.2, 1.3, 1,4 and next.
